dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
addons:
  apt:
    packages:
    - rpm
install:
  - npm install
script:
  - npm test
deploy:
  provider: script
  skip_cleanup: true
  script: electron-forge publish
  on:
    branch:
      - master
